CPR products generation code
aodn/public-schema pull request #28
Opened 2021-12-21 05:03 UTC by leonardolaiolo

2022-01-11 04:38 UTC, leonardolaiolo commented
@mhidas here the pipeline config file for the CPR products. I did not push the file to the `octopus` branch because it is not an open pull request or draft, so cannot contribute with an extra commit, unless I open a draft pull request that I'm not sure it's your plan.
```
    "id": "IMOS_CPR_DB",
    "path": [ "IMOS_CPR_DB" ],
    "handler": "ImosBgcDbHandler",
    "params": {
        "include_regexes": [
            ".*\\.csv$"
        ],
        "harvest_params": {
            "db_schema": "imos_cpr_db",
            "db_objects": [
                {
                    "name": "cpr_samp",
                    "type": "table"
                },
                {
                    "name": "cpr_phyto_raw",
                    "type": "table"
                },
                {
                    "name": "cpr_phyto_changelog",
                    "type": "table"
                },
                {
                    "name": "cpr_zoop_raw",
                    "type": "table"
                },
                {
                    "name": "cpr_zoop_changelog",
                    "type": "table"
                },
                {
                    "name": "cpr_phytoplankton_map",
                    "type": "materialized view",
                    "dependencies": [
			"cpr_samp",
		        "cpr_phyto_raw"]
                },
                {
                    "name": "cpr_phytoplankton_abundance_raw_data",
                    "type": "materialized view",
                    "dependencies": ["cpr_phyto_raw"]
                },
                {
                    "name": "cpr_phytoplankton_abundance_species_data",
                    "type": "materialized view",
                    "dependencies": [
			"cpr_phyto_raw",
			"cpr_phyto_changelog"]
                },
                {
                    "name": "cpr_phytoplankton_abundance_genus_data",
                    "type": "materialized view",
                    "dependencies": [
                        "cpr_phyto_raw",
                        "cpr_phyto_changelog"]
                },
                {
                    "name": "cpr_phytoplankton_abundance_htg_data",
                    "type": "materialized view",
                    "dependencies": ["cpr_phyto_raw"]
                },
                {
                    "name": "cpr_zooplankton_map",
                    "type": "materialized view",
                    "dependencies": [
                        "cpr_samp",
                        "cpr_zoop_raw"]
                },
                {
                    "name": "cpr_zooplankton_abundance_raw_data",
                    "type": "materialized view",
                    "dependencies": ["cpr_zoop_raw"]
                },
                {
                    "name": "cpr_zooplankton_abundance_genus_data",
                    "type": "materialized view",
                    "dependencies": [
                        "cpr_zoop_raw",
                        "cpr_zoop_changelog"]
                },
                {
                    "name": "cpr_zooplankton_abundance_htg_data",
                    "type": "materialized view",
                    "dependencies": ["cpr_zoop_raw"]
                },
                {
                    "name": "cpr_zooplankton_abundance_copepods_data",
                    "type": "materialized view",
                    "dependencies": [
                        "cpr_samp",
                        "cpr_zoop_raw",
                        "cpr_zoop_changelog"
                    ]
                },
                {
                    "name": "cpr_zooplankton_abundance_non_copepods_data",
                    "type": "materialized view",
                    "dependencies": [
                        "cpr_samp",
                        "cpr_zoop_raw",
                        "cpr_zoop_changelog"
                    ]
                },
                {
                    "name": "cpr_phytoplankton_biovolume_raw_data",
                    "type": "materialized view",
                    "dependencies": [
                        "cpr_samp",
                        "cpr_phyto_raw"
                    ]
                },
                {
                    "name": "cpr_phytoplankton_biovolume_species_data",
                    "type": "materialized view",
                    "dependencies": [
                        "cpr_samp",
                        "cpr_phyto_raw",
                        "cpr_phyto_changelog"
                    ]
                },
                {
                    "name": "cpr_phytoplankton_biovolume_genus_data",
                    "type": "materialized view",
                    "dependencies": [
                        "cpr_samp",
                        "cpr_phyto_raw",
                        "cpr_phyto_changelog"
                    ]
                },
                {
                    "name": "cpr_phytoplankton_biovolume_htg_data",
                    "type": "materialized view",
                    "dependencies": [
                        "cpr_samp",
                        "cpr_phyto_raw"
                    ]
                }
	    ]
        }
    }
}
```

2022-02-24 02:27 UTC, mhidas requested changes
I haven't done a full review, just looking at timestamp formatting...

2022-02-24 02:27 UTC, mhidas commented on cpr_data/cpr_zooplankton_map.sql
> +    s.sampledateutc AT TIME ZONE 'UTC' AS "SampleDate_UTC",
Don't need `AT TIME ZONE 'UTC'` - same as in [`bgc_trip_metadata`](https://github.com/aodn/public-schema/blob/c6e65f83fbbb7f64a88b78f5582b87dc28c04676/bgc_data/bgc_trip_metadata.sql#L10)

2022-03-07 06:14 UTC, mhidas commented on cpr_data/cpr_phytoplankton_map.sql
> +    to_char(sampledateutc, 'HH24:MI') AS "Time_UTC24hr",
According to the product spec, these should all be "_local", not UTC.

2022-03-07 06:40 UTC, mhidas commented on cpr_data/cpr_phytoplankton_map.sql
> +          trip_code IN (SELECT DISTINCT trip_code from cpr_phyto_raw)
This needs last condition needs to use the `sample` column, which is what actually links the `cpr_phyto_raw` table back to `cpr_samp` (`trip_code` doesn't even exist in the former - the only reason this subquery doesn't break is it's interpreted to mean `cpr_samp.trip_code`, which makes this whole condition equivalent to `TRUE`)
```suggestion
          sample IN (SELECT DISTINCT sample from cpr_phyto_raw)
```

2022-03-07 07:00 UTC, mhidas commented
I've fixed the couple of issues I mentioned in my recent comments.

Here's a complete set of products generated by the current code:
[cpr_products.zip](https://github.com/aodn/public-schema/files/8195489/cpr_products.zip)

2022-03-15 21:58 UTC, clairedavies commented
this all looks good to me.
the only issue is with some change log information that I need to decide how to deal with, I can make these changes and they will flow through automatically.

2022-03-16 03:13 UTC, mhidas approved these changes

2022-03-16 03:13 UTC, merged